### ISSUE TITLE
react-native: Does not work when minified (release-mode)

### ISSUE THREAD

**Issue by acuntex** [cimdalli/redux-ts#1]
When using redux-ts in a react-native application and you create a release build, the bundle gets minified.
Because of this, the reducers apparently don't get called.

I guess it is because redux-ts uses the class name of the action as string which gets scrambled because of the minification?

**Comment by acuntex** [comment]
Further information: It is probably because of uglifyjs with mangle = true

**Comment by cimdalli** [comment]
@acuntex you are right, because of minification class names are scrambled. To avoid it, if you use webpack, you can use that configuration:

```js
new webpack.optimize.UglifyJsPlugin({
  mangle: {
    keep_fnames: true
  }
})
```

**Comment by fwh1990** [comment]
I don't think it's the best solution. The developer should not care about this and framework should resolve it. I recommend you ave a look at [redux-model](https://github.com/fwh1990/redux-model), this framework also use class names and compatible with all scenarios.
