### ISSUE TITLE
TypeError after updating to Version 4.3.0

### ISSUE THREAD

**Issue by KTDevelopment** [cimdalli/redux-ts#9]
Hi I just build some annotations based extension for your package. (https://github.com/KTDevelopment/redux-ts-annotations)

sadly after the update to 4.3.0 there is some crazy error occuring. the Problem is, it just says "TypeError".

It Look like it's something about "Connect" function of react-redux.
as for version 4.1.8 i got the following log output when using a class decorator
 ```
 console.log node_modules/reflect-metadata/Reflect.js:542
    decorated:  function Connect(props) {
            var _this;
    
            _this = _OuterBaseComponent.call(this, props) || this;
            (0, _invariant.default)(forwardRef ? !props.wrapperProps[storeKey] : !props[storeKey], 'Passing redux store in props has been removed and does not do anything. ' + customStoreWarningMessage);
            _this.selectDerivedProps = makeDerivedPropsSelector();
            _this.selectChildElement = makeChildElementSelector();
            _this.indirectRenderWrappedComponent = _this.indirectRenderWrappedComponent.bind((0, _assertThisInitialized2.default)(_this));
            return _this;
          }
```

with 4.3.0 i got:

```
  console.log node_modules/reflect-metadata/Reflect.js:542
    decorated: { '$$typeof': Symbol(react.memo),
      type: [Function: ConnectFunction],
      compare: null,
      WrappedComponent: [Function: TodoComponent],
      displayName: 'Connect(TodoComponent)' }
```

as i have seen you updated react-redux to version 7 from 6 are there any breaking changes, that may explain this problem you may know?

**Comment by cimdalli** [comment]
Problem is not directly related with redux-ts but react-redux library. In fact, it is the case that decorator is requiring function and if decorated object is not in function type, it throws error with no detail. 
[`reflect-metadata` L:542](https://github.com/rbuckton/reflect-metadata/blob/3aeb98af4030be664a66f49bfd164936e0ba1825/Reflect.js#L544)
```js
if (!IsUndefined(decorated) && !IsNull(decorated)) {
    if (!IsConstructor(decorated))
        throw new TypeError();
    target = decorated;
}
``` 

I guess, in previous version of react-redux, connect had returned function type, but it changed in version. One possible workaround to force it to return function is passing `pure: false` value to connect method.

```js
 return connect(
    exportMapState(propType),
    exportMapDispatcher(propType),
    null,
    { pure: false }
  )(compType)
```
